cargo-features = ["edition2024"]

[package]
name = "ephemeral-rollup-counter-program"
version = "0.1.0"
edition = "2024"

[lib]
crate-type=["cdylib", "lib"]

[dependencies]
borsh = "1.5.1"
ephemeral-rollups-sdk = "0.2.4"
solana-program = "2.1.21"


